### ISSUE TITLE
Zoom location on hint click

### ISSUE THREAD

**Issue by taijuten** [laurenashpole/react-inner-image-zoom#21]
Currently the zoom is focused on wherever the user clicks.

However, when clicking on the zoom hint (as a button) the user is zoomed into the bottom right (or wherever CSS places it).

I feel like this should be central, as it's unlikely in this case that the user wants to be zoomed to the corner.

**Comment by laurenashpole** [comment]
Hey! Sorry I'm so slow seeing this and responding. 

This is an interesting suggestion. Right now the magnifying glass is meant more as a visual hint that can't be interacted with but I'm not sure what the most common UX pattern is. I might need to do some research around the bigger online retails sites.

**Comment by 41y08h** [comment]
> Hey! Sorry I'm so slow seeing this and responding.
> 
> This is an interesting suggestion. Right now the magnifying glass is meant more as a visual hint that can't be interacted with but I'm not sure what the most common UX pattern is. I might need to do some research around the bigger online retails sites.

You should show `Click to zoom` with the magnifying glass image somewhere instead of just an image.

**Comment by laurenashpole** [comment]
Hey @41y08h,

One of the reasons I opted for an importable stylesheet instead of inlining the styling was to hopefully make it easier to make changes like this just with CSS overrides. If you want to add text to the hint, you should be able to do it with something like:

```css
.iiz__hint {
  width: auto;
  padding: 0 10px;
}

.iiz__hint:after {
  content: 'Click to zoom';
  padding-left: 10px;
}
```

 That's a pretty basic example but you can use that class to customize and add emphasis to the magnifying glass.
