### ISSUE TITLE
Zoom functionality broken with overlay

### ISSUE THREAD

**Issue by bhavikagrawal** [laurenashpole/react-inner-image-zoom#29]
I am trying to implement an overlay on click of zoom of image.

The `afterZoomIn`  event fires but image does not zoom in. When i close the overlay and try to zoom in or out. It does not work.

Code: https://codesandbox.io/s/inner-image-zoom-sjfz5

I found the problem. Once the overlay is closed, it does not read the current pointer location, thus does not trigger the zoom in functionality.

**Comment by bhavikagrawal** [comment]
I have raised a PR with proposed changes: #30

**Comment by laurenashpole** [comment]
Hey @bhavikagrawal,

Thinking it over, I believe the expected behavior would be for zooming to be disabled when another element is blocking the image (although I may need to double check that re-zooming still works once that element is removed). So firing an overlay on `afterZoomIn` should cause the image to zoom out again.

In the CodeSandbox example you included, if you want zooming to continue with the overlay on top and stop when the user clicks, you should be able to get that effect by adding the style `pointer-events: none` to your overlay and using `afterZoomOut={() => setSayHello(false)}` with the InnerImageZoom component to close the overlay.

**Comment by bhavikagrawal** [comment]
@laurenashpole Thanks, i now understand what i missed.
