### ISSUE TITLE
Close on tap  - mobile

### ISSUE THREAD

**Issue by mrajewski** [laurenashpole/react-inner-image-zoom#34]
Hi, first of all i want to thank you for such a nice project. 
However i struggle a bit with some settings. Is there any option for disable close button on mobile devices and instead use just tap for closing zoomed view ? 

I've made full screen modal with images and want to close zoom in this particular way.

![mobile](https://user-images.githubusercontent.com/51779809/107758149-c66ab980-6d26-11eb-930d-48fbe012eccd.jpg)

**Comment by laurenashpole** [comment]
Hey, thanks for your kind words!

This took a little while to get in because I've been in the middle of a big React hooks refactor. _But_, that just went out and I included this functionality with it. If you pass in the prop `hideCloseButton` it'll keep the button from rendering and switch the zoom out trigger to on click (which should behave the same as tap).

If you give it a try, let me know if you run into any bugs with the new version. Thanks!

**Comment by mrajewski** [comment]
Thats awesome ! I already tested it and it works like a charm thank you so much ! I'm also very happy to see few others new changes in the latest version :)
