### ISSUE TITLE
imgAttributes bug

### ISSUE THREAD

**Issue by DanielStasyuk** [laurenashpole/react-inner-image-zoom#89]
Version 3.0.0

When I passed alt to the InnerImageZoom component and tried to find alt text by unit test(Jest), it didn't find it.
In docs I found that I can pass alt and some other props through imgAttributes. But in fact InnerImageZoomProps component doesn't have imgAttributes in props interface. It has only alt. 
![image](https://user-images.githubusercontent.com/77619671/151186073-d2aa7940-513c-486d-a09c-18a963e5cc77.png)

And when I passed alt, it doesn't work, because it didn't pass to the imgAttributes.
![image](https://user-images.githubusercontent.com/77619671/151187406-6081ad59-a272-4deb-a174-b9fe63f6c68e.png)
![image](https://user-images.githubusercontent.com/77619671/151188065-6f78c1f8-e5ad-4b23-b16e-fc2b82414c37.png)

And the only not best practice way that remains for it to make it work looks like that:
![image](https://user-images.githubusercontent.com/77619671/151187944-10987c21-8b7f-4489-a87a-7734267d3374.png)

**Comment by laurenashpole** [comment]
I don't believe this is a bug with the component. The `alt` prop was deprecated with the v3.0.0 release and `imgAttributes` should be used for that and any other image attributes going forward. 

This package hasn't been updated in [Definitely Typed](https://github.com/DefinitelyTyped/DefinitelyTyped) since the major version change. To use type definitions, you'll have to either wait for an update there or use v2.1.0 for now.

**Comment by DanielStasyuk** [comment]
Got it. It makes sense, thanks!

**Comment by laurenashpole** [comment]
Hey @DanielStasyuk, you motived me to work on getting those type definitions updated. I'm getting a [branch](https://github.com/laurenashpole/DefinitelyTyped/tree/react-inner-image-zoom-v3) ready to make a PR into Definitely Typed and was wondering if I could convince you to give the new definitions a try since you have a project going. If you have time, the file is [here](https://github.com/laurenashpole/DefinitelyTyped/blob/2a3e4ff808bf9333906e3ac64fb0fae1357bde7f/types/react-inner-image-zoom/index.d.ts), if not I'll open the PR and hopefully they'll be released before too long. Thanks!

**Comment by DanielStasyuk** [comment]
@laurenashpole Hey, sorry for replying so late. I`ve tested these types a bit and they work well
